USE ROLE ACCOUNTADMIN;

CREATE SCHEMA IF NOT EXISTS BRONZE;

USE SCHEMA BRONZE;

CREATE TABLE IF NOT EXISTS CICD_PRODUCTS (
    PRODUCT_ID INTEGER,
    PRODUCT_NAME STRING,
    CATEGORY STRING,
    PRICE NUMBER(10,2)
);