USE ROLE ACCOUNTADMIN;

CREATE MASKING POLICY IF NOT EXISTS BRONZE.CICD_MASK_PRICE
AS (val NUMBER(10,2))
RETURNS NUMBER(10,2) ->
    CASE
        WHEN CURRENT_ROLE() = 'ACCOUNTADMIN' THEN val
        ELSE NULL
    END;

ALTER TABLE BRONZE.CICD_PRODUCTS
    ALTER COLUMN PRICE
    SET MASKING POLICY BRONZE.CICD_MASK_PRICE;
