{{ config(materialized='table') }}

SELECT
    p.CATEGORY,
    SUM(o.QUANTITY * p.PRICE) AS TOTAL_REVENUE,
    COUNT(*) AS ORDER_COUNT,
    APPROX_COUNT_DISTINCT(o.CUSTOMER_ID) AS UNIQUE_CUSTOMERS
FROM {{ ref('stg_orders') }} AS o
INNER JOIN RETAIL_LAKEHOUSE.BRONZE.PRODUCTS AS p
    ON o.PRODUCT_ID = p.PRODUCT_ID
WHERE o.ORDER_STATUS <> 'CANCELLED'
GROUP BY p.CATEGORY
ORDER BY p.CATEGORY