{{ config(materialized='table') }}

SELECT
    ORDER_ID,
    CUSTOMER_ID,
    PRODUCT_ID,
    COALESCE(QUANTITY, 0)::INTEGER AS QUANTITY,
    UPPER(TRIM(ORDER_STATUS)) AS ORDER_STATUS,
    ORDER_TS::TIMESTAMP_NTZ AS ORDER_TS
FROM RETAIL_LAKEHOUSE.BRONZE.ORDERS
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY ORDER_ID
    ORDER BY ORDER_TS DESC
) = 1